runtime: nodejs
env: flex

# ovo je samo za testiranje/isprobavanje
# downgrejdam sve živo da bi bilo što jeftinije :-)

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10